service: senior-project-template
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    USERS_TABLE: users
    PROJECTS_TABLE: projects
    TIMESHEET_TABLE: timesheet
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:Scan
          Resource:
            - !GetAtt UsersTable.Arn
            - !GetAtt ProjectsTable.Arn
            - !GetAtt TimesheetTable.Arn

  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:4200
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - OPTIONS
      allowCredentials: false        
            
plugins:
  - serverless-offline

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

# Project Table for storing Projects and who is in each project
    ProjectsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: projects
        AttributeDefinitions:
          - AttributeName: project_name
            AttributeType: S
        KeySchema:
          - AttributeName: project_name
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    

    TimesheetTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: timesheet
        AttributeDefinitions:
          - AttributeName: project_name
            AttributeType: S
          - AttributeName: timeframe
            AttributeType: S
        KeySchema:
          - AttributeName: project_name
            KeyType: HASH
          - AttributeName: timeframe
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

functions:
  login:
    handler: src/handlers/login.handler
    events:
      - httpApi:
          path: /login
          method: post
  createUser:
    handler: src/handlers/create_user.handler
    events:
      - httpApi:
          path: /newUser
          method: post
  createProject:
    handler: src/handlers/create_project.handler
    events:
      - httpApi:
          path: /newProject
          method: post
  getProjects:
    handler: src/handlers/get_projects.handler
    events:
      - httpApi:
          path: /projects
          method: get
  getTimesheet:
    handler: src/handlers/get_timesheet.handler
    events:
      - httpApi:
          path: /getTimesheet
          method: post
  saveTimesheet:
    handler: src/handlers/save_timesheet.handler
    events:
      - httpApi:
          path: /saveTimesheet
          method: post
  

